version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: insecure_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5454"

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5454
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: insecure_db
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  db_data: