version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: insecure_db
    ports:
      - "5454:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ../../backend
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: insecure_db
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build: ../../frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  db_data: